# Generated by Django 5.0.3 on 2024-03-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('NdaConta', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.TextField(max_length=30)),
                ('Cpfs', models.TextField(max_length=11)),
                ('Saldo', models.FloatField()),
            ],
        ),
    ]
