# Generated by Django 5.0.3 on 2024-03-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_DressBank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='UsuariosConta',
        ),
    ]
