# Generated by Django 5.0.3 on 2024-03-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_DressBank', '0002_rename_usuarios_usuariosconta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuariosConta',
            new_name='usuario',
        ),
    ]
