# Generated by Django 5.0.3 on 2024-03-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_DressBank', '0003_rename_usuariosconta_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Saldo',
        ),
    ]
