# Generated by Django 5.0.3 on 2024-03-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_DressBank', '0004_remove_usuario_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Cpfs',
            new_name='Cpf',
        ),
    ]
