# Generated by Django 5.0.3 on 2024-03-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_DressBank', '0005_rename_cpfs_usuario_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Cpf',
            new_name='cpf',
        ),
    ]
