# Generated by Django 5.0.3 on 2024-03-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_DressBank', '0007_pix_rename_nome_usuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='saldo',
            field=models.FloatField(default=3000),
        ),
    ]
