# Generated by Django 5.0.3 on 2024-03-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_DressBank', '0009_alter_usuario_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pix',
            name='dia',
            field=models.DateField(auto_now_add=True),
        ),
    ]
