# Generated by Django 5.0.3 on 2024-03-27 02:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_DressBank', '0010_alter_pix_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pix',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
