# Generated by Django 5.0.3 on 2024-03-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_DressBank', '0011_alter_pix_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='saldo',
            field=models.FloatField(default=0, null=True),
        ),
    ]
