# Generated by Django 5.0.3 on 2024-03-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_DressBank', '0015_alter_usuario_cpf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pix',
            new_name='Pagamentos',
        ),
    ]
