# Generated by Django 5.0.3 on 2024-04-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_DressBank', '0017_alter_pagamentos_dia_alter_pagamentos_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentos',
            name='destinovalor',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='dia',
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='hora',
            field=models.TextField(default=1),
        ),
    ]
