# Generated by Django 5.0.3 on 2024-04-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_DressBank', '0018_alter_pagamentos_destinovalor_alter_pagamentos_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentos',
            name='dia',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='hora',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.TextField(max_length=200),
        ),
    ]
